on:
  push:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.ssl-backend || 'native' }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release', ssl-backend: openssl}
          - {os: windows-latest, r: 'release'}
          - {os: windows-2019,   r: 'release'}
          - {os: ubuntu-20.04,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - shell: bash
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - shell: Rscript {0}
        run: |
          install.packages('curl', repos = 'https://cran.r-project.org')

      - shell: Rscript {0}
        run: |
          h <- curl::new_handle(verbose=TRUE,sslversion=6L)
          curl::curl_fetch_memory('https://crandb.r-pkg.org/dplyr/all', handle = h)
        env:
          CURL_SSL_BACKEND: ${{ matrix.config.ssl-backend }}
